# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daco < Formula
  desc "Swiss army knife for data product projects"
  homepage "https://github.com/dacolabs/cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dacolabs/cli/releases/download/v0.1.2/daco_0.1.2_darwin_amd64.tar.gz"
      sha256 "3374aff1ebf8a456b67d191d22acd451f653c13f67b39e38b826e24345255a3c"

      def install
        bin.install "daco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dacolabs/cli/releases/download/v0.1.2/daco_0.1.2_darwin_arm64.tar.gz"
      sha256 "0a867aa9c0fa77030c739fca7090cc6f866a1d780eb67c416cc7749047355b3e"

      def install
        bin.install "daco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacolabs/cli/releases/download/v0.1.2/daco_0.1.2_linux_amd64.tar.gz"
      sha256 "4125a984597277a63589bad0fec39d0c7c4882ff3b3e46321e3b87a3ea7b5111"
      def install
        bin.install "daco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dacolabs/cli/releases/download/v0.1.2/daco_0.1.2_linux_arm64.tar.gz"
      sha256 "4f50e26484edb317cab4d4d7d7d4b5a0c674cfa36cbfa9676cba4cec6198bfe7"
      def install
        bin.install "daco"
      end
    end
  end

  test do
    system "#{bin}/daco", "--version"
  end
end
